version: "3"

services:
  client:
    container_name: storespacefood
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/app
    ports:
      - "3003:80"
    networks:
      - main

networks:
  main:
    driver: bridge
    external: true
