export const GET_MENU = "GET_MENU"
export const CREATE_MENU = "CREATE_MENU"
export const UPDATE_MENU = "UPDATE_MENU"
export const GET_ALL_INGREDIENTS = "GET_ALL_INGREDIENTS"
export const ERROR = "ERROR"
export const FILTER = "FILTER"
export const GET_INGREDIENT_ID = "GET_INGREDIENT_ID";
export const LOGIN_STATUS = "LOGIN_STATUS";
export const CREATE_INGREDIENTS = "CREATE_INGREDIENTS";


